LibraryManagementSystem/Controllers/AuthorController.cs
using LibraryManagementSystem.Entities;
using LibraryManagementSystem.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Hosting.Server;
using Microsoft.AspNetCore.Mvc;
using System.Reflection;

namespace LibraryManagementSystem.Controllers
{
    public class AuthorController : Controller
    {
        

        private readonly IWebHostEnvironment _webHostEnvironment;

        public AuthorController(IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult List()             //Yazarları listelerken kullanılan action
        {
            var viewModel = StaticClass._authors.Where(x => x.IsDeleted == false).Select(x => new AuthorListViewModel           //AuthorListViewModel modeli kullanılarak listeleme işlemi yapılır
            {
                Id = x.Id,
                FirstName = x.FirstName,
                LastName = x.LastName,
                ImageUrl = x.ImageUrl,


            }).ToList();
            return View(viewModel);
        }

        public IActionResult Details(int id)            //Detayda book ve author tabloları birleştirilerek artık author tarafında da book nesneleri view'e taşınabilir
        {
            var viewModel = StaticClass._authors.Where(x => x.Id == id).Select(x => new AuthorListViewModel
            {
                FirstName = x.FirstName,
                LastName = x.LastName,
                ImageUrl = x.ImageUrl,
            }).FirstOrDefault();

            if (viewModel is null)
            {
                return NotFound();
            }


            return View(viewModel);


        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Authors = StaticClass._authors;
            return View();

        }

        [HttpPost]
        public async Task<IActionResult> Create(AuthorCreateViewModel model)
        {
            if (!ModelState.IsValid)             //Modele uymuyorsa yine aynısını geri döndür
            {
                return View();
            }
            int maxId = StaticClass._authors.Max(x => x.Id);

            // Yazar oluşturulurken resim dosyası eklenebilmesi için
            // Eğer dosya yüklendiyse
            if (model.ImageUrl != null && model.ImageUrl.Length > 0)
            {
                // Dosya adını alma
                string fileName = Path.GetFileNameWithoutExtension(model.ImageUrl.FileName);
                string extension = Path.GetExtension(model.ImageUrl.FileName);
                fileName = fileName + extension;

                // Dosyanın sunucuda kaydedileceği yol
                string uploadPath = Path.Combine(_webHostEnvironment.WebRootPath, "images");

                // Eğer dizin yoksa oluştur
                if (!Directory.Exists(uploadPath))
                {
                    Directory.CreateDirectory(uploadPath);
                }

                // Tam dosya yolu
                string filePath = Path.Combine(uploadPath, fileName);

                // Dosyayı kaydetme
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await model.ImageUrl.CopyToAsync(fileStream);
                }

                // Burada model.ImageFile yerine dosyanın sunucuda kaydedildiği `filePath`'i saklayabilir veya veritabanına kaydedebilirsiniz.
            }


            var newAuthor = new AuthorEntity()
            {
                Id = maxId + 1,
                FirstName = model.FirstName,
                LastName = model.LastName,
                ImageUrl = "../images/" + model.ImageUrl.FileName
                
                
            };
            StaticClass._authors.Add(newAuthor);

           
            return RedirectToAction("List");
            // Eğer model geçersizse formu yeniden göster
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var author = StaticClass._authors.Find(x=> x.Id == id);

            var viewModel = new AuthorEditViewModel()
            {

               Id = author.Id,
               FirstName = author.FirstName,
               LastName = author.LastName
              

            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(AuthorEditViewModel formData)
        {
            if (!ModelState.IsValid)
            {                
                return View(formData);
            }

            if (formData.ImageUrl != null && formData.ImageUrl.Length > 0)
            {
                // Dosya adını alma
                string fileName = Path.GetFileNameWithoutExtension(formData.ImageUrl.FileName);
                string extension = Path.GetExtension(formData.ImageUrl.FileName);
                fileName = fileName + extension;

                // Dosyanın sunucuda kaydedileceği yol
                string uploadPath = Path.Combine(_webHostEnvironment.WebRootPath, "images");

                // Eğer dizin yoksa oluştur
                if (!Directory.Exists(uploadPath))
                {
                    Directory.CreateDirectory(uploadPath);
                }

                // Tam dosya yolu
                string filePath = Path.Combine(uploadPath, fileName);

                // Dosyayı kaydetme
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await formData.ImageUrl.CopyToAsync(fileStream);
                }

                // Burada model.ImageFile yerine dosyanın sunucuda kaydedildiği `filePath`'i saklayabilir veya veritabanına kaydedebilirsiniz.
            }

            var author = StaticClass._authors.Find(x => x.Id == formData.Id);

            author.FirstName = formData.FirstName;
            author.LastName = formData.LastName;
            author.ImageUrl = "../images/" + formData.ImageUrl.FileName;



            return RedirectToAction("List");

        }


        [HttpGet]
        public IActionResult ConfirmDelete(int id)
        {
            var author = StaticClass._authors.Find(x => x.Id == id);
            if (author != null)
            {
                ViewBag.AuthorTitle = author.FirstName +" "+ author.LastName; // Kitap başlığını view'a gönderiyoruz
            }

            var viewModel = new AuthorDeleteViewModel
            {
                AuthorId = author.Id,
                FirstName = author.FirstName,
                LastName = author.LastName,
                
            };

            return View("Delete", viewModel);               //Id yi tutabilmek için model de gönderildi

        }


        // Silme işlemi
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var author = StaticClass._authors.Find(x => x.Id == id);
            if (author != null)
            {
                author.IsDeleted = true;
                TempData["DeleteMessage"] = $"{author.FirstName + author.LastName} başarıyla silindi.";
            }
            return RedirectToAction("List");
        }




    }

}

LibraryManagementSystem/Controllers/BookController.cs
using LibraryManagementSystem.Entities;
using LibraryManagementSystem.Models;
using Microsoft.AspNetCore.Mvc;

namespace LibraryManagementSystem.Controllers
{
    public class BookController : Controller
    {
       
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult List()             //Kitapları listeleme actionı
        {
            var viewModel = StaticClass._books.Where(x => x.IsDeleted == false)
                .Join(
                StaticClass._authors,
                book => book.AuthorId,
                author => author.Id,
                (book, author) => new { book, author }).Select(x => new BookListViewModel       //silinmemiş kitapları seçerek ilgili viewmodele projekte ederek listelenir
                {
                    Id = x.book.Id,
                    Title = x.book.Title,
                    AuthorName = x.author.FirstName + " " + x.author.LastName,
                    Genre = x.book.Genre,
                    PublishDate = x.book.PublishDate
                }).ToList();


            return View(viewModel);
        }
        public IActionResult Details(int id)        //Kitap detayını gösteren action
        {
            var viewModel = StaticClass._books.Where(x => x.Id == id)
                .Join(
                StaticClass._authors,
                book => book.AuthorId,
                author => author.Id,
                (book, author) => new { book, author }).Select(x => new BookListViewModel       //silinmemiş kitapları seçerek ilgili viewmodele projekte ederek listelenir
                {
                    Id = x.book.Id,
                    Title = x.book.Title,
                    AuthorName = x.author.FirstName + " " + x.author.LastName,
                    Genre = x.book.Genre,
                    PublishDate = x.book.PublishDate
                }).FirstOrDefault();                //Tek bir eleman geleceği için



            if (viewModel is null)
            {
                return NotFound();
            }



            return View(viewModel);

        }
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Authors = StaticClass._authors.Select(a => new              //veriyi view'e taşırken isim ve soyismi fullname değişkeni altında taşıması için
            {
                Id = a.Id,
                FullName = $"{a.FirstName} {a.LastName}"
            });

            return View();
        }

        [HttpPost]
        public IActionResult Create(BookCreateViewModel formData)         //Kitap oluşturma actionı
        {
            if (!ModelState.IsValid)             //Modele uymuyorsa yine aynısını geri döndür
            {
                return View();
            }
            int maxId = StaticClass._books.Max(x => x.Id);

            var newBook = new BookEntity()
            {
                Id = maxId + 1,
                Title = formData.Title,
                AuthorId = formData.AuthorId,
                Genre = formData.Genre,
                PublishDate = formData.PublishDate,
            };
            StaticClass._books.Add(newBook);


            return RedirectToAction("List");

        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var book = StaticClass._books.Find(x => x.Id == id);

            var viewModel = new BookEditViewModel()
            {
                
                Title = book.Title,
                
                Genre = book.Genre,
                PublishDate = book.PublishDate,
            };

            ViewBag.Authors = StaticClass._authors;

            return View(viewModel);

        }

        [HttpPost]
        public IActionResult Edit(BookEditViewModel formData)
        {
            if (!ModelState.IsValid)
            {
                return View(formData);
            }

            var book = StaticClass._books.Find(x => x.Id == formData.Id);

            book.Title = formData.Title;
            book.Genre = formData.Genre;
            book.PublishDate = formData.PublishDate;



            return RedirectToAction("List");

        }

        [HttpGet]
        public IActionResult ConfirmDelete(int id)
        {
            var book = StaticClass._books.Find(x => x.Id == id);
            if (book != null)
            {
                ViewBag.BookTitle = book.Title; // Kitap başlığını view'a gönderiyoruz
            }

            var viewModel = new BookDeleteViewModel
            {
                BookId = book.Id,
                Title = book.Title,
            };

            return View("Delete", viewModel);               //Id yi tutabilmek için model de gönderildi
         
        }
        

        // Silme işlemi
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var book = StaticClass._books.Find(x => x.Id == id);
            if (book != null)
            {
                book.IsDeleted = true;
                TempData["DeleteMessage"] = $"{book.Title} başarıyla silindi.";
            }
            return RedirectToAction("List");
        }


    }
}

LibraryManagementSystem/Views/Book/Create.cshtml
@model BookCreateViewModel

<h3>Yeni Kitap Giriş Sayfası</h3>
@if (User.Claims.FirstOrDefault(x => x.Type == "id")?.Value != null)
{
    <form method="post" asp-controller="Book" asp-action="Create">
        <div>
            <label>Kitap İsmi</label>
            <input asp-for="Title" class="form-control" type="text" />
            <span asp-validation-for="Title" class="text-danger mt-2 fw-bold"></span>
        </div>

        <div>
            <label>Kitap Türü</label>
            <textarea asp-for="Genre" rows="4" class="form-control"></textarea>
            <span asp-validation-for="Genre" class="text-danger mt-2 fw-bold"></span>
        </div>

        <div>
            <label>Yayın Tarihi</label>
            <textarea asp-for="PublishDate" rows="4" class="form-control"></textarea>
            <span asp-validation-for="PublishDate" class="text-danger mt-2 fw-bold"></span>
        </div>
        <div>
            <label>Yazar</label>
            <select asp-for="AuthorId" asp-items="@(new SelectList(ViewBag.Authors , "Id","FullName"))" class="form-control">
                <option selected disabled>Yazar ismi seçiniz</option>
            </select>
            <span asp-validation-for="AuthorId" class="text-danger mt-2 fw-bold"></span>
        </div>



        <button type="submit" class="btn btn-success mt-2">Kaydet</button>

    </form>
}

LibraryManagementSystem/Views/Book/Delete.cshtml
@model BookDeleteViewModel

@{
    ViewBag.Title = "Silme Onayı";
}

<!-- Bootstrap Modal -->
<div class="modal fade" id="confirmDeleteModal" tabindex="-1" aria-labelledby="confirmDeleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmDeleteModalLabel">Silme İşlemi</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                @ViewBag.BookTitle - silmek istediğinize emin misiniz?
            </div>
            <div class="modal-footer">
                <form asp-action="Delete" method="post">
                    <input type="hidden" name="id" value="@Model.BookId" />
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" onclick="location.href='@Url.Action("List", "Book")'">Hayır</button>
                    <button type="submit" class="btn btn-danger">Evet, Sil</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Modal'ı otomatik açmak için script -->
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var confirmDeleteModal = new bootstrap.Modal(document.getElementById('confirmDeleteModal'));
        confirmDeleteModal.show();
    });
</script>

LibraryManagementSystem/Views/Book/Details.cshtml
@model BookListViewModel


@if (User.Claims.FirstOrDefault(x => x.Type == "id")?.Value != null)
{

    <div class="card">
        <div class="card-header blockquote fw-bold ">
            @Model.Id Numaralı Kitap Detayları
        </div>
        <div class="card-body">
            <blockquote class=" mb-4 fw-bold">
                <p>Kitap İsmi : @Model.Title</p>
                <p>Kitap Yazarı : @Model.AuthorName</p>

                <p>Kitap Türü : @Model.Genre</p>
                <p>Kitap Yayın Tarihi : @Model.PublishDate.Year</p>


            </blockquote>
        </div>
    </div>


    <a asp-action="List" asp-controller="Book" class="btn btn-outline-warning fw-bold">
        Geri Dön
    </a>
}

LibraryManagementSystem/Views/Book/Edit.cshtml
@model BookEditViewModel

@if (User.Claims.FirstOrDefault(x => x.Type == "id")?.Value != null)
{
    <h3>Kitap Düzenleme Sayfası</h3>

    <form method="post" asp-controller="Book" asp-action="Edit">
        <input type="hidden" asp-for="Id" />

        <div>
            <label>Kitap İsmi</label>
            <input asp-for="Title" class="form-control" type="text" />
            <span asp-validation-for="Title" class="text-danger mt-2 fw-bold"></span>
        </div>

        <div>
            <label>Kitap Türü</label>
            <textarea asp-for="Genre" rows="4" class="form-control"></textarea>
            <span asp-validation-for="Genre" class="text-danger mt-2 fw-bold"></span>
        </div>

        <div>
            <label>Yayın Tarihi</label>
            <textarea asp-for="PublishDate" rows="4" class="form-control"></textarea>
            <span asp-validation-for="PublishDate" class="text-danger mt-2 fw-bold"></span>
        </div>



        <button type="submit" class="btn btn-success mt-2">Kaydet</button>

    </form>
}

LibraryManagementSystem/Views/Book/Index.cshtml
<div class="container">
    <div class="alert alert-warning alert-dismissible fade show">
        <strong> Hoş Geldin!</strong>  @User.Claims.FirstOrDefault(x => x.Type == "email")?.Value -
        @User.Claims.FirstOrDefault(x => x.Type == "id")?.Value


    </div>
</div>
<h1>Kütüphane Yönetim Sistemine Hoşgeldiniz</h1>
<div class="col-md-12">
    <img src="~/images/banner.jpg" class="img-fluid w-100" alt="Banner Görseli">
</div>
<hr />

@if (User.Claims.FirstOrDefault(x => x.Type == "id")?.Value != null)
{

    <div class="alert alert-primary d-flex align-items-center" role="alert">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle me-2" viewBox="0 0 16 16">
            <path d="M7.938 2.016a.13.13 0 0 1 .125 0l6.857 11.856c.03.05.048.108.048.167a.25.25 0 0 1-.25.25H1.25a.25.25 0 0 1-.25-.25c0-.059.017-.116.048-.167L7.938 2.016zM8 4.5c-.535 0-.954.462-.9.995l.35 3.507c.058.575.516 1.014 1.05 1.014h.1c.534 0 .993-.439 1.05-1.014l.35-3.507c.054-.533-.365-.995-.9-.995H8zm0 8a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
        </svg>
        <strong> Kitap Eklemek istiyorsanız ilk olarak kitap yazarını eklemelisiniz!</strong>
    </div>



    <div class="row justify-content-center">
        <div class="col-sm-6 col-md-4 mb-3 mb-sm-0">
            <div class="card" style="width: 18rem;">
                <img src="~/images/kitap.jpg" class="card-img-top" alt="kitap">
                <div class="card-body">
                    <a asp-controller="Book" asp-action="List" class="btn btn-info">Kitap Listesini Görmek İçin Tıklayınız</a>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-4">
            <div class="card" style="width: 18rem;">
                <img src="~/images/yazar.jpg" class="card-img-top" alt="yazar">
                <div class="card-body">
                    <a asp-controller="Author" asp-action="List" class="btn btn-info">Yazar Listesini Görmek İçin Tıklayınız</a>
                </div>
            </div>
        </div>
    </div>
}

LibraryManagementSystem/Views/Book/List.cshtml
@model List<BookListViewModel>

<h3>Kitap Listesi</h3>

@if (User.Claims.FirstOrDefault(x => x.Type == "id")?.Value != null)
{


    <div class="mb-3">
        @foreach (var book in Model)
        {
            <div class="card">
                <div class="card-header fw-bold">
                    @book.Title
                </div>
                <div class="card-body">
                    <h6 class="card-title">@book.AuthorName</h6>


                    <p class="card-text">@book.Genre</p>
                    <a asp-controller="Book" asp-action="Details" asp-route-id="@book.Id" class="btn btn-info">Detay</a>
                    <a asp-controller="Book" asp-action="Edit" asp-route-id="@book.Id" class="btn btn-secondary">Düzenle</a>
                    <a asp-controller="Book" asp-action="ConfirmDelete" asp-route-id="@book.Id" class="btn btn-danger">Sil</a>


                </div>
            </div>

        }



    </div>
    <div>
        <a asp-controller="Book" asp-action="Create" class="btn btn-success fw-bold mb-3">Yeni Ekle</a>
    </div>
}